# Generated by Django 4.0.5 on 2022-06-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default='eeb4d0e00a38e8cd5610', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
