# Generated by Django 4.0.5 on 2022-06-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default='4255ef219ead9056639d', editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
