# Generated by Django 4.0.5 on 2022-06-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_account_balance_alter_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default='7c737b3e508627b0aedc', editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
