# Generated by Django 4.0.5 on 2022-06-09 15:27

import bank.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_alter_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default=bank.utils.create_random_string_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
